### ISSUE TITLE
DBIish shall not create table in the database

### ISSUE THREAD

**Issue by zoffixznet** [raku-community-modules/DBIish#77] opened 2016-12-04 05:10 UTC
Moved from [RT#129951](https://rt.perl.org/Ticket/Display.html?id=129951)

```
When DBIish gets installed it created a table sal_emp or similar. I just guess
it was DBIish, as that was the last thing I installed before I have got
problem with the database.

Namely, the third party software has opened PostgreSQL and inserted table
without asking. It broke the web interface to that database. If there
are some testings to be done, that shall be asked prior to testing
being conducted.

Jean
```

The tests should not mess with user's stuff without permission. An env var should be added and avoid running any intrusive tests if it's not set.

**Comment by jonathanstowe** [comment] 2016-12-08 22:24
This is because the environment variable ```PGDATABASE``` was set when the tests were run, otherwise it would have made the table in a different database.  This should a) be documented better and b) probably use a different variable name like ```DBISH_TEST_PGDATABASE``` or something.

**Comment by jonathanstowe** [comment] 2016-12-08 22:32
Ah, the PGDATABASE variable is used by the pg library itself, I think we need to do something different in the tests so that it doesn't use them unless the user requests it with say ```DBISH_USE_ENVIRONMENT```

**Comment by zoffixznet** [comment] 2016-12-08 22:40
> otherwise it would have made the table in a different database

If it does that, then it shouldn't. The env var should control whether a test is done at all.

**Comment by abraxxa** [comment] 2016-12-08 23:08
The question is why you have a database server running which isn't secured properly so that any program can access it and run even DDL statements?!

**Comment by zoffixznet** [comment] 2016-12-08 23:13
> The question is why you have a database server running which isn't secured properly so that any program can access it and run even DDL statements?!

That's a very poor question 😸

**Comment by salortiz** [comment] 2016-12-09 00:11
Some facts:

- `DBDish::Pg` honor all *documented* PostgreSQL environment variables as a deliberated decision. This is documented, among other places, at https://github.com/perl6/DBIish/blob/master/t/35-pg-common.t#L25 
-  During testing the tables are created in the default `PUBLIC` schema.
-  Basic tests should be non-interactive and run unattended.
-  The naming of the tables used in testing was based on the names of Oracle's standard test tables

If some production system broke as a result of a table created that way, that is because it is using the defaults of the database cluster, a bad idea, or the installation was done using the environment of that system, a worse one.

So, unless someone convinces me otherwise, I'll be closing this as "not a bug"

**Comment by zoffixznet** [comment] 2016-12-09 00:35
I can add another three facts:

* We have an actual user whose system this module destroyed... and we don't have a that huge number of users for this to be a freak accident
* You're making an assumption your tests are perfect and there's no chance for you to introduce a bug that will create/destroy stuff you didn't intend it to.
* I personally only ever use this module for SQLite, but because I have both PG and MySQL installed, this module runs all of those tests every time, despite the fact that I couldn't care less about them. Them failing would mean nothing to me, but it would abort installation of this module.

> If some production system broke [...]

And what if it's a development system that broke? You say you use Oracle's standard test table, which is so much more likely others' development system would be using them as well. 

> So, unless someone convinces me otherwise

To me, the fact that a user can destroy their system by merely installing the module is a convincing-enough argument that a module is broken. You have your development system. You have Travis. You have Appveyor. And, as part of Rakudo Star, this module undergoes testing on each release as well. There's plenty of opportunity for thorough testing of the module, without putting an unwitting user at risk.

**Comment by bazzaar** [comment] 2016-12-09 01:11
Is part of the issue here related to the DBIish module being bundled in Rakudo Star, without there being adequate links to documentation of the module on the Rakudo star installation page? Is that also an issue for all other bundled modules too?

I for one, have PG installed, admittedly as a hobbyist, and Rakudo Star installing on the same machine, and I try to have the PG server running at the time. I've not had a problem with database corruption, as a result of the tests. That's just my personal experience, I'm not implying what others should expect.

Regards,
Barry

**Comment by AlexDaniel** [comment] 2016-12-09 01:20
Documentation will not resolve this issue.

**Comment by salortiz** [comment] 2016-12-09 02:44
@zoffixznet,

I never assumed nor claimed that the tests are perfect! In fact they are not "my tests". But IMO the tests uses a reasonable approach, the same well established one used by P5's DBI.

Moreover, you claim that the tests *destroyed* a system seems to me a bit exaggerated. I would like to know the details of the original reported failure.

I'm open to review/discuss/implement any concrete recommendation, I just do not think the request, as stated in the title above, is reasonable.

PD: If you don't need/use PG or MySQL, you can turn their engines off and the tests will be skipped.

**Comment by adaptiveoptics** [comment] 2016-12-09 05:27
I use DBIish in a production environment and have never had a problem. I don't use or allow any environment variables for auth purposes either, though. And I believe that people who do should expect trouble from all over.

That being said, my tests that rely on databases always require a special environment variable to be set before they work. I think there is no easy best answer for this.

**Comment by jonathanstowe** [comment] 2016-12-09 07:26
I actually agree with nearly *all* the points above, it is likely that the system in question would have been broken by any software that tried to test against the database, the module is just following the documented behaviour of the libpg and assumes that the user knows what they are  doing if they have ```PGDATBASE``` set in the environment.  However I think we need to do better than that and actually make it **hard** for the user to use DBIish to do the inevitable foot shooting in this circumstance.

So I propose that

      * we alter the tests to never use the PG environment variables unless they have set some other ```DBISH_USE_PG_ENVIRONMENT ```` possibly display some diag to say that is what is happening.
      * Provide an alternative set ot environment variables for the database and user
     * document clearly in the POD and README that the module follows this behaviour through no fault of its own

We should consider the environment to untrusted, we don't want to see ourselves starring in a CERT advisory.

**Comment by JJ** [comment] 2020-05-27 15:49
Maybe we should get back to this one? Following @jonathanstowe advice, for instance.

**Comment by rbt** [comment] 2020-05-27 16:35
Some modules use an environment variable AUTHOR_TESTING=YES or NETWORK_TESTING=YES to enable testing.

Would a single DB_TESTING=YES variable be sufficient to cover all databases (MySQL, Oracle, Pg)?

For Pg, the env variables we do use is insufficient. I set PG_HOST which is handled by libpq rather than the tests.PG_SERVICE is also a common flag and we ignore it entirely.

In the mean time, I'll convert tests to use temporary tables which will reduce the amount of cruft that can be left behind.

**Closed** 2020-06-01 15:32 UTC
